### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by hkjels** [gonewest818/dimmer.el#2]
There's a performance degradation for almost every operation after activating dimmer

**Comment by gonewest818** [comment]
Can you share your .emacs.d ? I’m not seeing the same degradation, but based on your comment in #1, I also don’t use the same packages.

**Comment by hkjels** [comment]
Sure https://github.com/hkjels/.eyre/

**Comment by gonewest818** [comment]
Thanks.  I ran a quick profile and found a bunch of redundant calculations. It's computing the dimmed versions of the same faces over and over again. So first of all, I'm going to lazily cache the dimmed faces because it's deterministic and there are a finite set of faces. After that I'll try to test with your config.

**Comment by gonewest818** [comment]
Try pulling from the master branch. I sort of have your Eyre config installed here, but I'm pretty hopelessly lost with your keybindings so I'm not able to learn much that way. But as I said, I did some optimizations and found at least one performance related bug, so my hope is the experience is better now.

**Comment by hkjels** [comment]
Emacs is now back to normal in terms of performance.
I didn't even know I wanted a package like `dimmer` until I stumbled onto it.
This is really great!

**Comment by gonewest818** [comment]
Great! Thanks for being an early adopter and sending the big reports and feedback.
