### ISSUE TITLE
Dimming windows instead of buffers

### ISSUE THREAD

**Issue by Patryk27** [gonewest818/dimmer.el#58]
Hi 🙂 

It seems like dimmer.el internally relies on buffer name, which means that e.g. splitting a buffer into separate windows causes all of those windows to remain highlighted (since all are backed by the same buffer), instead of highlighting only one of them (the one where the caret is / the one with active modeline):

![image](https://user-images.githubusercontent.com/3395477/140925479-837181cb-e80b-448e-bcd6-90c35626b332.png)

Could this behavior be somehow configurable?

Thanks for this package,
Cheers.

**Comment by gonewest818** [comment]
Hi Patryk.  Indeed I would prefer if dimmer could do this, but Emacs doesn't have the ability to set window-specific face remaps.  I'm limited to setting the "dimmed" face at the the buffer level.  Thanks-

**Comment by Patryk27** [comment]
Aw, yeah, if that's a fundamental thing, then we're out of luck; well, thanks for responding! 🙂

**Comment by strobe** [comment]
> Hi Patryk. Indeed I would prefer if dimmer could do this, but Emacs doesn't have the ability to set window-specific face remaps. I'm limited to setting the "dimmed" face at the the buffer level. Thanks-

It looks like is not true anymore. 

I noticed that another dimming package doing that https://github.com/mina86/auto-dim-other-buffers.el and its doc mention that is available since version 27.

Emacs doc  has some info about that https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Remapping.html

Seems it's required to use :filtered in order to apply remapping to specific window.

here is how it used in  auto-dim-other-buffers: 
https://github.com/mina86/auto-dim-other-buffers.el/blob/master/auto-dim-other-buffers.el#L143

@gonewest818 please check.
